export const schedule = [
  {
    day: "Sun",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "GJ",
        name: "Gillian J.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "MK",
        name: "Max K.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "ED",
        name: "Eric D.",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
  {
    day: "Mon",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "GJ",
        name: "Gillian J.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "MK",
        name: "Max K.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "PN",
        name: "Phil N.",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
  {
    day: "Tue",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "M",
        name: "Mac",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "MK",
        name: "Max K.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "PN",
        name: "Phil N",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
  {
    day: "Wed",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "M",
        name: "Mac",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "MK",
        name: "Max K.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "PN",
        name: "Phil N.",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
  {
    day: "Thurs",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "M",
        name: "Mac",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "JB",
        name: "James B.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "ED",
        name: "Eric D.",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
  {
    day: "Fri",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "GJ",
        name: "Gillian J.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "JB",
        name: "James B.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "PN",
        name: "Phil N.",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
  {
    day: "Fri",
    shifts: [
      {
        start: "07:45",
        end: "13:45",
        initials: "GJ",
        name: "Gillian J.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "13:45",
        end: "19:45",
        initials: "MK",
        name: "Max K.",
        role: "Barista",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
      {
        start: "19:45",
        end: "04:00",
        initials: "PN",
        name: "Eric D.",
        role: "Bartender",
        duration: "6 hr",
        location: "Bushwick Public House",
      },
    ],
  },
];